<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Employee Registration</title>

<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: black;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

/* Full-width input fields */
select{
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}
</style>
</head>
<body>

	<form action="/employee/saveReg" id="form1">
	  <div class="container">
	    <h1>Register New Manager</h1>
	    <p>EmployeeID is automatically generated by system</p>
	    <hr>
		
		<label for="employeeID"><b>EmployeeID</b></label>
	    <input type="text" name="employeeID" value='<c:out value="${newID}"></c:out>' readonly id="eID">
		
	    <label for="fname"><b>First Name</b></label>
	    <input type="text" placeholder="Enter FirstName" name="fname" required id="firstName">
	
	    <label for="lname"><b>Last Name</b></label>
	    <input type="text" placeholder="Enter LastName" name="lname" required id="lastName">
	
	    <label for="position"><b>Select Position</b></label>
	    <select name="postn" id="position">
	  		<c:forEach var="posL" items="${posList}">
	    		<option value='<c:out value="${posL.posTitle}"></c:out>'>${posL.posTitle}</option>
	    	</c:forEach>
	  	</select>
	    
	    
	    <label for="department"><b>Select Department</b></label>
	    <select name="dept" id="department">
	  		<c:forEach var="deptL" items="${departmentList}">
	    		<option value='<c:out value="${deptL.department}"></c:out>'>${deptL.department}</option>
	    	</c:forEach>
	  	</select>
	  	
	  	<label for="manager"><b>Select Manager</b></label>
	    <select name="mngr" id="manager">
    		<option value=${manager.id} selected>${manager.managerFName} ${manager.managerLName}</option>
	  	</select>
	  	
	  	<label for="EmplType"><b>Employment Type</b></label>
	    <select name="emplType" id="emplType">
	  		<option value="Permanent">Permanent</option>
		  	<option value="Contingent">Contingent</option>
		  	<option value="Internship">Internship</option>
		  	<option value="Contractor">Contractor</option>
	  	</select>	
	
	  	<label for="mEmel"><b>Employee Email</b></label>
	    <input type="text" name="mEmel" value='nash95.helmi@gmail.com' readonly id="emel">
	    
	    <hr>
	    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>
	
	    <button type="submit" class="registerbtn">Register</button>
	  </div>
	</form>
	
<script type="text/javascript">
	function concatName(fname,lname){
		
	}	
</script>
</body>
</html>