<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: black;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

/* Full-width input fields */
select{
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}
</style>
</head>
<body>

<form action="/manager/saveUpd">
  <div class="container">
    <h1>Update Manager Details</h1>
    <p>ManagerID is automatically generated by system</p>
    <hr>
	
	<label for="managerID"><b>ManagerID</b></label>
    <input type="text" name="managerID" value='<c:out value="${manager.id}"></c:out>' readonly>
	
    <label for="fname"><b>First Name</b></label>
    <input type="text" name="fname" value='<c:out value="${manager.managerFName}"></c:out>'>

    <label for="lname"><b>Last Name</b></label>
    <input type="text" name="lname" value='<c:out value="${manager.managerLName}"></c:out>'>
	
	<label for="position"><b>Select Position</b></label>
    <select name="postn">
  		<c:forEach var="posL" items="${pList}">
      		<option value="${posL.posTitle}" ${ posL.posTitle == selectedPosL ? 'selected' : ''}>${posL.posTitle}</option>	
    	</c:forEach>
  	</select>
    
    <label for="department"><b>Select Department</b></label>
    <select name="dept">
  		<c:forEach var="deptL" items="${dList}">
    		<option value="${deptL.department}" ${ deptL.department == selectedDeptL ? 'selected' : ''}>${deptL.department}</option>
    	</c:forEach>
  	</select>
  	
  	<label for="mEmel"><b>Manager Email</b></label>
    <input type="text" name="mEmel" value='nash95.helmi@gmail.com' readonly>
    
    <hr>
    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

    <button type="submit" class="registerbtn">Update</button> 
    
  </div>
  
  <div class="container signin">
    <p>Already have an account? <a href="#">Sign in</a>.</p>
  </div>
</form>

<script>
	function SaveUpdate(){
		window.location.href("http://localhost:8083/manager/findAll")
		}
</script>
</body>
</html>